using System;
using System.Collections.Generic;
using System.Linq;
using GestionComerce.Main.Facturation;

namespace GestionComerce.Helpers
{
    /// <summary>
    /// Unified data aggregator for article statistics across Operations and Invoices
    /// </summary>
    public class ArticleDataAggregator
    {
        private readonly List<Operation> operations;
        private readonly List<OperationArticle> operationArticles;
        private readonly List<Invoice> invoices;
        private readonly List<Article> articles;

        public ArticleDataAggregator(
            List<Operation> operations,
            List<OperationArticle> operationArticles,
            List<Invoice> invoices,
            List<Article> articles)
        {
            this.operations = operations ?? new List<Operation>();
            this.operationArticles = operationArticles ?? new List<OperationArticle>();
            this.invoices = invoices ?? new List<Invoice>();
            this.articles = articles ?? new List<Article>();
        }

        #region Core Aggregation Methods

        /// <summary>
        /// Gets total units sold for an article from BOTH operations and invoices
        /// </summary>
        public int GetTotalUnitsSold(int articleId, DateTime startDate, DateTime endDate)
        {
            int operationSales = GetOperationSales(articleId, startDate, endDate);
            int invoiceSales = GetInvoiceSales(articleId, startDate, endDate);

            System.Diagnostics.Debug.WriteLine($"Article {articleId}: Operations={operationSales}, Invoices={invoiceSales}");

            return operationSales + invoiceSales;
        }

        /// <summary>
        /// Gets total units purchased for an article from operations
        /// </summary>
        public int GetTotalUnitsPurchased(int articleId, DateTime startDate, DateTime endDate)
        {
            var purchases = operationArticles
                .Where(oa => oa.ArticleID == articleId &&
                            !oa.Reversed &&
                            operations.Any(o => o.OperationID == oa.OperationID &&
                                              o.OperationType != null &&
                                              o.OperationType.StartsWith("A", StringComparison.OrdinalIgnoreCase) &&
                                              o.DateOperation >= startDate &&
                                              o.DateOperation <= endDate))
                .Sum(oa => oa.QteArticle);

            return purchases;
        }

        /// <summary>
        /// Gets revenue generated by an article from BOTH sources
        /// </summary>
        public decimal GetTotalRevenue(int articleId, DateTime startDate, DateTime endDate)
        {
            decimal operationRevenue = GetOperationRevenue(articleId, startDate, endDate);
            decimal invoiceRevenue = GetInvoiceRevenue(articleId, startDate, endDate);

            return operationRevenue + invoiceRevenue;
        }

        /// <summary>
        /// Gets profit margin for an article (revenue - cost)
        /// </summary>
        public decimal GetTotalProfit(int articleId, DateTime startDate, DateTime endDate)
        {
            var article = articles.FirstOrDefault(a => a.ArticleID == articleId);
            if (article == null) return 0;

            int unitsSold = GetTotalUnitsSold(articleId, startDate, endDate);
            int unitsPurchased = GetTotalUnitsPurchased(articleId, startDate, endDate);

            decimal revenue = GetTotalRevenue(articleId, startDate, endDate);
            decimal cost = article.PrixAchat * unitsPurchased;

            return revenue - cost;
        }

        /// <summary>
        /// Gets daily sales velocity (units per day) for predictive analytics
        /// </summary>
        public double GetSalesVelocity(int articleId, DateTime startDate, DateTime endDate)
        {
            int totalSold = GetTotalUnitsSold(articleId, startDate, endDate);
            double days = (endDate - startDate).TotalDays;

            if (days <= 0) return 0;

            return totalSold / days;
        }

        #endregion

        #region Top Performers

        /// <summary>
        /// Gets top selling articles by quantity
        /// </summary>
        public List<ArticlePerformance> GetTopSellingArticles(DateTime startDate, DateTime endDate, int topN = 5)
        {
            var performance = new Dictionary<int, ArticlePerformance>();

            // Aggregate from both sources
            foreach (var article in articles.Where(a => a.Etat))
            {
                int unitsSold = GetTotalUnitsSold(article.ArticleID, startDate, endDate);

                if (unitsSold > 0)
                {
                    performance[article.ArticleID] = new ArticlePerformance
                    {
                        ArticleID = article.ArticleID,
                        ArticleName = article.ArticleName,
                        UnitsSold = unitsSold,
                        Revenue = GetTotalRevenue(article.ArticleID, startDate, endDate),
                        Profit = GetTotalProfit(article.ArticleID, startDate, endDate)
                    };
                }
            }

            return performance.Values
                .OrderByDescending(p => p.UnitsSold)
                .Take(topN)
                .ToList();
        }

        /// <summary>
        /// Gets top revenue-generating articles
        /// </summary>
        public List<ArticlePerformance> GetTopRevenueArticles(DateTime startDate, DateTime endDate, int topN = 5)
        {
            var performance = new Dictionary<int, ArticlePerformance>();

            foreach (var article in articles.Where(a => a.Etat))
            {
                decimal revenue = GetTotalRevenue(article.ArticleID, startDate, endDate);

                if (revenue > 0)
                {
                    performance[article.ArticleID] = new ArticlePerformance
                    {
                        ArticleID = article.ArticleID,
                        ArticleName = article.ArticleName,
                        UnitsSold = GetTotalUnitsSold(article.ArticleID, startDate, endDate),
                        Revenue = revenue,
                        Profit = GetTotalProfit(article.ArticleID, startDate, endDate)
                    };
                }
            }

            return performance.Values
                .OrderByDescending(p => p.Revenue)
                .Take(topN)
                .ToList();
        }

        /// <summary>
        /// Gets revenue by article family (category)
        /// </summary>
        public Dictionary<int, FamilyPerformance> GetRevenueByFamily(DateTime startDate, DateTime endDate)
        {
            var familyData = new Dictionary<int, FamilyPerformance>();

            foreach (var article in articles.Where(a => a.Etat))
            {
                decimal revenue = GetTotalRevenue(article.ArticleID, startDate, endDate);
                int unitsSold = GetTotalUnitsSold(article.ArticleID, startDate, endDate);

                if (!familyData.ContainsKey(article.FamillyID))
                {
                    familyData[article.FamillyID] = new FamilyPerformance
                    {
                        FamilyID = article.FamillyID,
                        TotalRevenue = 0,
                        TotalUnitsSold = 0,
                        ArticleCount = 0
                    };
                }

                familyData[article.FamillyID].TotalRevenue += revenue;
                familyData[article.FamillyID].TotalUnitsSold += unitsSold;
                familyData[article.FamillyID].ArticleCount++;
            }

            return familyData;
        }

        #endregion

        #region Private Helper Methods

        private int GetOperationSales(int articleId, DateTime startDate, DateTime endDate)
        {
            return operationArticles
                .Where(oa => oa.ArticleID == articleId &&
                            !oa.Reversed &&
                            operations.Any(o => o.OperationID == oa.OperationID &&
                                              o.OperationType != null &&
                                              o.OperationType.StartsWith("V", StringComparison.OrdinalIgnoreCase) &&
                                              !o.Reversed &&
                                              o.DateOperation >= startDate &&
                                              o.DateOperation <= endDate))
                .Sum(oa => oa.QteArticle);
        }

        private int GetInvoiceSales(int articleId, DateTime startDate, DateTime endDate)
        {
            return invoices
                .Where(i => i.InvoiceDate >= startDate &&
                           i.InvoiceDate <= endDate &&
                           !i.IsDeleted &&
                           !i.IsReversed &&
                           i.Articles != null)
                .SelectMany(i => i.Articles)
                .Where(ia => ia.ArticleID == articleId &&
                            !ia.IsDeleted &&
                            !ia.IsReversed)
                .Sum(ia => (int)ia.Quantite);
        }

        private decimal GetOperationRevenue(int articleId, DateTime startDate, DateTime endDate)
        {
            var article = articles.FirstOrDefault(a => a.ArticleID == articleId);
            if (article == null) return 0;

            var sales = operationArticles
                .Where(oa => oa.ArticleID == articleId &&
                            !oa.Reversed &&
                            operations.Any(o => o.OperationID == oa.OperationID &&
                                              o.OperationType != null &&
                                              o.OperationType.StartsWith("V", StringComparison.OrdinalIgnoreCase) &&
                                              !o.Reversed &&
                                              o.DateOperation >= startDate &&
                                              o.DateOperation <= endDate))
                .ToList();

            return sales.Sum(oa => article.PrixVente * oa.QteArticle);
        }

        private decimal GetInvoiceRevenue(int articleId, DateTime startDate, DateTime endDate)
        {
            return invoices
                .Where(i => i.InvoiceDate >= startDate &&
                           i.InvoiceDate <= endDate &&
                           !i.IsDeleted &&
                           !i.IsReversed &&
                           i.Articles != null)
                .SelectMany(i => i.Articles)
                .Where(ia => ia.ArticleID == articleId &&
                            !ia.IsDeleted &&
                            !ia.IsReversed)
                .Sum(ia => ia.TotalTTC);
        }

        #endregion

        #region Stock Prediction Methods

        /// <summary>
        /// Predicts days until stockout based on current velocity
        /// </summary>
        public double GetDaysUntilStockout(int articleId, int currentStock)
        {
            var article = articles.FirstOrDefault(a => a.ArticleID == articleId);
            if (article == null || article.IsUnlimitedStock)
                return double.PositiveInfinity;

            // Calculate velocity over last 30 days
            DateTime endDate = DateTime.Now;
            DateTime startDate = endDate.AddDays(-30);

            double velocity = GetSalesVelocity(articleId, startDate, endDate);

            if (velocity <= 0)
                return double.PositiveInfinity;

            return currentStock / velocity;
        }

        /// <summary>
        /// Gets recommended reorder quantity based on velocity
        /// </summary>
        public int GetRecommendedReorderQuantity(int articleId, int daysOfSupply = 30)
        {
            var article = articles.FirstOrDefault(a => a.ArticleID == articleId);
            if (article == null || article.IsUnlimitedStock)
                return 0;

            DateTime endDate = DateTime.Now;
            DateTime startDate = endDate.AddDays(-30);

            double velocity = GetSalesVelocity(articleId, startDate, endDate);

            return (int)Math.Ceiling(velocity * daysOfSupply);
        }

        #endregion
    }

    #region Data Transfer Objects

    public class ArticlePerformance
    {
        public int ArticleID { get; set; }
        public string ArticleName { get; set; }
        public int UnitsSold { get; set; }
        public decimal Revenue { get; set; }
        public decimal Profit { get; set; }
        public decimal ProfitMargin => Revenue > 0 ? (Profit / Revenue) * 100 : 0;
    }

    public class FamilyPerformance
    {
        public int FamilyID { get; set; }
        public decimal TotalRevenue { get; set; }
        public int TotalUnitsSold { get; set; }
        public int ArticleCount { get; set; }
    }

    #endregion
}